CREATE TABLE Users (
	Id INT IDENTITY,
	UserName NVARCHAR(20) NOT NULL UNIQUE,
	[Password] NVARCHAR(30) NOT NULL,
	FullName NVARCHAR(100) NOT NULL,
	LastLogin DATETIME DEFAULT NULL
	CONSTRAINT PK_Users PRIMARY KEY(Id),
	CONSTRAINT CHK_Password CHECK (LEN([Password]) > =5))
GO
